sudo: false
language: node_js
node_js:
- '5.11'
cache:
  directories:
  - node_modules
before_script:
- npm prune
after_success:
- npm run coverage
- npm run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
  slack:
    secure: XI5lROrGT0KUg2J8aLZ79qeapUIDXde9fj1MagHlLYunFu1s3C0yDNReo9kGZwgpzM6yZ8fYHuq4roGR3jA3gWR9wGvNfwhcTFhFjNNK2ni49UchdNJ0z6fzS9hlQTVd/LiLfrrRo7zZmajVIKWZ5L6d+nqW/QnX2Ji0lnZ+CZqChiz/bx2FSJmapHTI9VMd9FoMy3C8QQb/tQDWPPhXZFkvrjEfK1DxSYmSm5mbNNdPz1NT7S1/dP35qK9Fni8YlS8OSoQO/Z6ROTsa5So8ZMWhMUAEEhfDYUWbSxFNb5tzdcctdALW/DgksYJZ+Zxmt7Htq44IjZCr8qj8On9k/7YeQH1rdJ1u1VQ9BgLtu5urP5AZGuIizhn6u42fhJ9faXfAzYe/GykR8t/1+V001I38Ec2VFlJwBnsaRgGX4Ushp5fQxir1IRRxz3ibTWUIoinHXeJ7HaW4aIt4sfQ1EXHddBXYNBraOfcq5lKCcZmGCITZ1dPU/Z6oAEe+Yhs5aYMHAkAS4Xd1SSRWZEuB8/ofIqBoIEfM6+PPQXxJl/2bMWEsIucnGcHAfcNzL4M0KQVXfJclywA9JN6wSDr78cTneau0GCS5O+9AHvY36n1fQzVUiQJTw9XbvWz4j77gAHHk5HVwQGYsyyL2/g4QYjdFDQPpvvv5kTQ9iWeijss=
